package control

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"
)

type LogDrainDeploymentService struct {
	projectRoot string
}

type LogDrainDeploymentOptions struct {
	ProjectRoot string
}

type LogDrainArtifact struct {
	Directory string `json:"directory"`
	Path      string `json:"path"`
}

func NewLogDrainDeploymentService() *LogDrainDeploymentService {
	return NewLogDrainDeploymentServiceWithOptions(LogDrainDeploymentOptions{})
}

func NewLogDrainDeploymentServiceWithOptions(opts LogDrainDeploymentOptions) *LogDrainDeploymentService {
	root := strings.TrimSpace(opts.ProjectRoot)
	if root == "" {
		root = os.Getenv("SUPADUPA_PROJECT_ROOT")
	}
	if root == "" {
		root = "./runtime/projects"
	}
	return &LogDrainDeploymentService{projectRoot: root}
}

func (s *LogDrainDeploymentService) Deploy(ctx context.Context, drain LogDrain) (LogDrainArtifact, error) {
	select {
	case <-ctx.Done():
		return LogDrainArtifact{}, ctx.Err()
	default:
	}
	if strings.TrimSpace(drain.ProjectRef) == "" {
		return LogDrainArtifact{}, fmt.Errorf("project ref is required")
	}
	if strings.TrimSpace(drain.ID) == "" {
		return LogDrainArtifact{}, fmt.Errorf("log drain id is required")
	}
	target, err := normalizeLogDrainTarget(drain.Target)
	if err != nil {
		return LogDrainArtifact{}, err
	}
	drain.Target = target
	if err := validateLogDrainConfig(drain.Target, drain.Config); err != nil {
		return LogDrainArtifact{}, err
	}

	dir := filepath.Join(s.projectRoot, drain.ProjectRef, "log-drains")
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return LogDrainArtifact{}, err
	}
	path := filepath.Join(dir, drain.ID+".toml")
	if err := os.WriteFile(path, []byte(renderLogDrainVectorSink(drain)), 0o600); err != nil {
		return LogDrainArtifact{}, err
	}
	return LogDrainArtifact{Directory: dir, Path: path}, nil
}

func (s *LogDrainDeploymentService) Delete(ctx context.Context, ref string, id string) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
	}
	ref = strings.TrimSpace(ref)
	id = strings.TrimSpace(id)
	if ref == "" {
		return fmt.Errorf("project ref is required")
	}
	if id == "" {
		return fmt.Errorf("log drain id is required")
	}
	return os.Remove(filepath.Join(s.projectRoot, ref, "log-drains", id+".toml"))
}

func renderLogDrainVectorSink(drain LogDrain) string {
	sinkName := logDrainSinkName(drain.ID)
	config := cloneStringMap(drain.Config)
	var builder strings.Builder
	fmt.Fprintf(&builder, "# Generated by supadupa. Do not edit by hand.\n")
	fmt.Fprintf(&builder, "[sinks.%s]\n", sinkName)
	switch drain.Target {
	case "datadog":
		writeTOMLKeyValue(&builder, "type", "datadog_logs")
		writeTOMLArray(&builder, "inputs", []string{"add_project"})
		writeTOMLKeyValue(&builder, "default_api_key", config["api_key"])
		if site := strings.TrimSpace(config["site"]); site != "" {
			writeTOMLKeyValue(&builder, "site", site)
		}
	case "loki":
		writeTOMLKeyValue(&builder, "type", "loki")
		writeTOMLArray(&builder, "inputs", []string{"add_project"})
		writeTOMLKeyValue(&builder, "endpoint", config["url"])
		fmt.Fprintf(&builder, "\n[sinks.%s.labels]\n", sinkName)
		writeTOMLKeyValue(&builder, "project_ref", drain.ProjectRef)
	case "s3":
		writeTOMLKeyValue(&builder, "type", "aws_s3")
		writeTOMLArray(&builder, "inputs", []string{"add_project"})
		writeTOMLKeyValue(&builder, "bucket", config["bucket"])
		if region := strings.TrimSpace(config["region"]); region != "" {
			writeTOMLKeyValue(&builder, "region", region)
		}
		prefix := strings.TrimSpace(config["prefix"])
		if prefix == "" {
			prefix = drain.ProjectRef + "/%Y/%m/%d/"
		}
		writeTOMLKeyValue(&builder, "key_prefix", prefix)
		fmt.Fprintf(&builder, "\n[sinks.%s.encoding]\n", sinkName)
		writeTOMLKeyValue(&builder, "codec", "json")
	default:
		writeTOMLKeyValue(&builder, "type", "http")
		writeTOMLArray(&builder, "inputs", []string{"add_project"})
		writeTOMLKeyValue(&builder, "uri", config["url"])
		writeTOMLKeyValue(&builder, "method", "post")
		fmt.Fprintf(&builder, "\n[sinks.%s.encoding]\n", sinkName)
		writeTOMLKeyValue(&builder, "codec", "json")
		if token := strings.TrimSpace(config["token"]); token != "" {
			fmt.Fprintf(&builder, "\n[sinks.%s.auth]\n", sinkName)
			writeTOMLKeyValue(&builder, "strategy", "bearer")
			writeTOMLKeyValue(&builder, "token", token)
		}
		writeLogDrainHTTPHeaders(&builder, sinkName, drain)
	}
	return builder.String()
}

func writeLogDrainHTTPHeaders(builder *strings.Builder, sinkName string, drain LogDrain) {
	fmt.Fprintf(builder, "\n[sinks.%s.request.headers]\n", sinkName)
	writeTOMLKeyValue(builder, "x-supadupa-project-ref", drain.ProjectRef)
	writeTOMLKeyValue(builder, "x-supadupa-log-drain-id", drain.ID)
}

func logDrainSinkName(id string) string {
	var builder strings.Builder
	builder.WriteString("log_drain_")
	for _, r := range id {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '_' {
			builder.WriteRune(r)
			continue
		}
		builder.WriteRune('_')
	}
	return strings.TrimRight(builder.String(), "_")
}

func writeTOMLKeyValue(builder *strings.Builder, key string, value string) {
	fmt.Fprintf(builder, "%s = %q\n", key, value)
}

func writeTOMLArray(builder *strings.Builder, key string, values []string) {
	quoted := append([]string(nil), values...)
	sort.Strings(quoted)
	for index, value := range quoted {
		quoted[index] = fmt.Sprintf("%q", value)
	}
	fmt.Fprintf(builder, "%s = [%s]\n", key, strings.Join(quoted, ", "))
}
