#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat >&2 <<'TXT'
usage: scripts/check-runtime-secret-hygiene.sh [--fail-on-present] [--markdown-report path] [repo-root]

Checks that local runtime secret artifacts are ignored and that top-level env
files are not group/world readable. The summary reports counts only; it never
prints secret file contents or secret values.
TXT
}

fail_on_present=false
markdown_report=""
repo_root="."

while [[ "$#" -gt 0 ]]; do
  case "$1" in
    --fail-on-present)
      fail_on_present=true
      shift
      ;;
    --markdown-report)
      markdown_report="${2:-}"
      if [[ -z "$markdown_report" ]]; then
        echo "--markdown-report requires a path" >&2
        exit 2
      fi
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    -*)
      echo "unknown option: $1" >&2
      usage
      exit 2
      ;;
    *)
      repo_root="$1"
      shift
      ;;
  esac
done

repo_root="$(cd "$repo_root" && pwd)"
cd "$repo_root"

count_find() {
  local path="$1"
  shift
  if [[ ! -e "$path" ]]; then
    printf '0'
    return
  fi
  find "$path" "$@" -print 2>/dev/null | wc -l | tr -d ' '
}

tracked_secret_paths="$(
  git ls-files -- .env '.env.*' runtime artifacts scripts/compat/artifacts scripts/compat/.artifacts 2>/dev/null \
    | grep -Ev '^\.env\.example$' || true
)"

status=0
if [[ -n "$tracked_secret_paths" ]]; then
  echo "Tracked secret-bearing paths must be removed from git:" >&2
  printf '%s\n' "$tracked_secret_paths" >&2
  status=1
fi

insecure_envs=()
while IFS= read -r env_file; do
  [[ -n "$env_file" ]] || continue
  mode="$(stat -c '%a' "$env_file")"
  if [[ "$mode" != "600" ]]; then
    insecure_envs+=("$env_file:$mode")
  fi
done < <(find . -maxdepth 1 -type f \( -name '.env' -o -name '.env.*' \) ! -name '*.env.example' -print 2>/dev/null)

if [[ "${#insecure_envs[@]}" -gt 0 ]]; then
  echo "Top-level env files must use mode 600:" >&2
  printf '%s\n' "${insecure_envs[@]}" >&2
  status=1
fi

top_env_count="$(count_find . -maxdepth 1 -type f \( -name '.env' -o -name '.env.*' \) ! -name '*.env.example')"
runtime_env_count="$(count_find runtime/projects -type f \( -name '.env' -o -name '*.env' \))"
backup_count="$(count_find runtime/backups -type f)"
cert_count="$(count_find runtime/certs -type f \( -name '*.crt' -o -name '*.key' -o -name '*.pem' -o -name 'acme.json' \))"
log_count="$(count_find . -type f -name '*.log' ! -path './node_modules/*' ! -path './frontend/node_modules/*')"

present_total=$(( top_env_count + runtime_env_count + backup_count + cert_count + log_count ))
tracked_status="$([[ -z "$tracked_secret_paths" ]] && echo ok || echo fail)"
decision_required="no"
if [[ "$present_total" -gt 0 ]]; then
  decision_required="yes"
fi

cat <<TXT
Runtime secret hygiene summary for $repo_root
tracked secret-bearing paths: $tracked_status
top-level env files: $top_env_count
runtime project env files: $runtime_env_count
backup artifacts: $backup_count
cert/key artifacts: $cert_count
log files: $log_count
TXT

if [[ -n "$markdown_report" ]]; then
  mkdir -p "$(dirname "$markdown_report")"
  cat >"$markdown_report" <<TXT
# Local Runtime Secret Artifact Inventory

Generated by:

\`\`\`sh
scripts/check-runtime-secret-hygiene.sh --markdown-report $markdown_report
\`\`\`

This report intentionally records counts and policy status only. It does not include secret values or a per-file inventory.

| Category | Count |
| --- | ---: |
| Top-level env files | $top_env_count |
| Runtime project env files | $runtime_env_count |
| Backup artifacts | $backup_count |
| Cert/key artifacts | $cert_count |
| Log files | $log_count |

Tracked secret-bearing paths: $tracked_status.

Owner decision required: $decision_required.

If these artifacts are disposable test state, stop local services and remove/regenerate the runtime tree. If any values are real, rotate affected project JWT secrets, database passwords, service-role keys, backup credentials, ACME/account material, provider tokens, and sessions before sharing the workspace or artifacts.
TXT
fi

if [[ "$fail_on_present" == "true" && "$present_total" -gt 0 ]]; then
  echo "Secret-bearing local artifacts are present." >&2
  status=1
elif [[ "$present_total" -gt 0 ]]; then
  echo "Local secret-bearing artifacts are present; keep them ignored and do not upload them."
fi

exit "$status"
